#!/usr/bin/env bash

echo "TODO......."
# =====================================
# TODO
# ====================================
# [] Link configrations
# 	[] bachup any old configraions 
# [] install needed fonts 
# [] install icons
# [] get wallpapers
# =====================================
